# docker-compose.yml

version: '3.8'

services:
  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
      - ./vendor:/var/www/html/vendor
      - ./app:/var/www/html/app
      - ./tests:/var/www/html/tests
    depends_on:
      - db
      - redis
  composer:
    image: composer:latest
    working_dir: /app
    volumes:
      - ./:/app
      - ./vendor:/app/vendor
  php-fpm-exporter:
    image: hipages/php-fpm_exporter:latest
    ports:
      - "${PHP_FPM_EXPORTER_PORT:-9253}:9253"
    command:
      - --phpfpm.scrape-uri=tcp://php:9000/status
    depends_on:
      - php


  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "${NGINX_PORT:-8080}:80"
    expose:
      - "80"
    environment:
      - NGINX_PORT=${NGINX_PORT:-8080}
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    ports:
      - "9113:9113"
    command:
      - "-nginx.scrape-uri=http://nginx:80/stub_status"
    depends_on:
      - nginx

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    
  grafana:
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "${TRAEFIK_PORT:-80}:80"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "${REDIS_EXPORTER_PORT:-9121}:9121"
    command:
      - "--redis.addr=redis:6379"
    depends_on:
      - redis

volumes:
  db_data:
  grafana_data: